package neth.iecal.curbox.data.sync

import com.google.gson.Gson
import com.google.gson.JsonObject
import org.junit.Assert.assertEquals
import org.junit.Assert.fail
import org.junit.Test

/**
 * Asserts the Android crypto produces the exact same bytes as the browser
 * extension, using the shared vectors generated by the extension's
 * crypto.test.ts. If this fails, the two platforms cannot read each other's
 * data.
 */
class CryptoBoxTest {

    private fun hex(s: String): ByteArray =
        ByteArray(s.length / 2) { ((s[it * 2].digitToInt(16) shl 4) or s[it * 2 + 1].digitToInt(16)).toByte() }

    @Test
    fun matchesExtensionVectors() {
        val raw = javaClass.classLoader!!.getResourceAsStream("crypto.vectors.json")!!
            .readBytes().decodeToString()
        val v = Gson().fromJson(raw, JsonObject::class.java)

        val params = v.getAsJsonObject("params")
        val kdf = CryptoBox.KdfParams(
            iterations = params.get("iterations").asInt,
            dkLenBits = params.get("dkLenBits").asInt,
        )
        val salt = hex(v.get("saltHex").asString)
        val dek = hex(v.get("dekHex").asString)
        val userId = v.get("userId").asString
        val expected = v.getAsJsonObject("expected")

        val kek = CryptoBox.deriveKekBytes(v.get("passphrase").asString, salt, kdf)
        assertEquals(expected.get("kekHex").asString, CryptoBox.toHex(kek))

        val wrapped = CryptoBox.wrapDek(kek, dek, userId, hex(v.get("wrapNonceHex").asString))
        assertEquals(expected.get("wrappedDekHex").asString, CryptoBox.toHex(wrapped))

        val aad = CryptoBox.recordAad(userId, v.get("namespace").asString, v.get("recordKey").asString)
        val record = CryptoBox.encryptRecord(dek, aad, v.get("plaintext").asString, hex(v.get("recordNonceHex").asString))
        assertEquals(expected.get("recordHex").asString, CryptoBox.toHex(record))

        // Round trips
        assertEquals(v.get("dekHex").asString, CryptoBox.toHex(CryptoBox.unwrapDek(kek, wrapped, userId)))
        assertEquals(v.get("plaintext").asString, CryptoBox.decryptRecord(dek, aad, record))
    }

    @Test
    fun rejectsTruncatedEncryptedBlobs() {
        val key = ByteArray(32)
        val aad = CryptoBox.recordAad("user", "namespace", "record")
        expectIllegalArgument { CryptoBox.decryptRecord(key, aad, byteArrayOf()) }
        expectIllegalArgument { CryptoBox.decryptRecord(key, aad, ByteArray(28)) }
    }

    @Test
    fun rejectsUnboundedOrUnsupportedKdfParameters() {
        val salt = ByteArray(16)
        expectIllegalArgument {
            CryptoBox.deriveKekBytes("phrase", salt, CryptoBox.KdfParams(iterations = 2_000_001))
        }
        expectIllegalArgument {
            CryptoBox.deriveKekBytes("phrase", salt, CryptoBox.KdfParams(alg = "scrypt"))
        }
        expectIllegalArgument {
            CryptoBox.deriveKekBytes("phrase", salt, CryptoBox.KdfParams(dkLenBits = 128))
        }
    }

    @Test
    fun rejectsOversizedPairingPayloadBeforeParsingIt() {
        expectIllegalArgument { CryptoBox.parsePairingPayload("x".repeat(2049)) }
    }

    private fun expectIllegalArgument(block: () -> Unit) {
        try {
            block()
            fail("expected IllegalArgumentException")
        } catch (_: IllegalArgumentException) {
        }
    }
}
